version: '3.7'
services:
  recipes:
    container_name: recipes
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 1235:1235
    environment:
      - CHOKIDAR_USEPOLLING=true
